exclude: ".*tests\/fixtures.*"
repos:
  - repo: https://github.com/google/yapf
    rev: v0.33.0
    hooks:
      - id: yapf
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
