# Configuration for big window tapes, like the demo
# These settings include a big window with gradient background, a colorful window bar, and a big font size

# --- Settings ------------------------
# Font
Set FontSize 20

# Terminal Size
Set Width 1200
Set Height 600

# Window
Set WindowBar "Colorful"
Set WindowBarSize 80
Set Padding 0

# Background
Set Margin 25
Set MarginFill ./configuration/gradient.png

# Window
Set BorderRadius 15
