name: Tests
on:
  - push
  - pull_request

jobs:
  testing-check:
    name: Run all tests with pytest
    runs-on: ubuntu-latest
    steps:
      # setup python
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install modules
        run: pip install -r requirements.txt -r requirements-dev.txt

      # run pytest
      - name: Run pytest
        run: python -m pytest
